#!/usr/bin/env python3

import os
import sys
import shutil
import tempfile
import subprocess
from pathlib import Path

# Git Utilities Installation Module (Python version)
# Installs custom git helper scripts for managing multiple identities

SCRIPT_DIR = Path(__file__).resolve().parent

def install_unconfigured(temp_dir, dest_dir):
    """Install scripts without configuration."""
    for script_name in ["git-init", "git-clone", "git-fix"]:
        src = temp_dir / script_name
        dest = dest_dir / script_name
        shutil.copy2(src, dest)
        dest.chmod(dest.stat().st_mode | 0o111) # Make executable
    
    print("Git utilities installed successfully (unconfigured)!")

def setup_interactive_config():
    """Build the configuration strings interactively."""
    print()
    print("Git/SSH identity setup (interactive)")
    print("This section allows you to configure multiple git identities and SSH keys.")
    print("Each identity consists of: key_name, email, and full name")
    print("Press Enter without input to skip or finish.")
    print("Format: key|email|name OR key,email,name")
    print()

    user_choices = []
    user_cases = []
    account_choices = []
    account_cases = []
    host_mappings = []
    
    idx = 0
    ssh_config_path = Path.home() / ".ssh" / "config"
    ssh_dir = Path.home() / ".ssh"

    while True:
        try:
            line = input("Enter identity (key|email|name or key,email,name), empty to finish: ").strip()
        except EOFError:
            break
            
        if not line:
            break
        
        # Normalize separators
        parts = line.replace('|', ',').split(',')
        if len(parts) != 3:
            print("WARNING: Invalid format. Expected: key|email|name or key,email,name")
            continue
            
        key, email, name = [p.strip() for p in parts]
        
        if not key or not email or not name:
             print("WARNING: All fields (key, email, name) are required.")
             continue

        # Generate SSH key if missing
        ssh_key_path = ssh_dir / f"id_ed25519_{key}"
        if not ssh_key_path.exists():
            print(f"Generating SSH key pair for {name} ({key})")
            try:
                subprocess.run([
                    "ssh-keygen", "-t", "ed25519", 
                    "-f", str(ssh_key_path), 
                    "-C", email, 
                    "-N", ""
                ], check=True)
                print(f"Public key: {ssh_key_path}.pub")
                print("Add this key to your GitHub/GitLab account")
            except subprocess.CalledProcessError as e:
                print(f"Error generating SSH key: {e}")
                continue

        # Ensure SSH config entry exists
        # We read the file to check for "Key -> key" marker
        current_config = ""
        if ssh_config_path.exists():
            current_config = ssh_config_path.read_text()

        marker = f"# Key -> {key}"
        if marker not in current_config:
            with open(ssh_config_path, "a") as f:
                f.write(f"\n{marker}\n")
                f.write(f"Host hub.{key}\n")
                f.write("    HostName github.com\n")
                f.write("    User git\n")
                f.write(f"    IdentityFile ~/.ssh/id_ed25519_{key}\n")

        idx += 1
        
        # Build strings for script patching
        # Matches bash logic: echo "1) Name"
        user_choices.append(f'echo "{idx}) {name}"')
        
        # Cases: 
        #     1)
        #         git config user.name "Name"
        #         git config user.email "email"
        #         ;;
        case_block = f"""    {idx})
        git config user.name "{name}"
        git config user.email "{email}"
        ;;"""
        user_cases.append(case_block)
        
        account_choices.append(f'echo "{idx}) {key}"')
        
        account_case_block = f"""    {idx})
        host_alias="{key}"
        ;;"""
        account_cases.append(account_case_block)
        
        host_mappings.append(f'host_map["{key}"]="hub.{key}"')

    return idx, user_choices, user_cases, account_choices, account_cases, host_mappings

def main():
    print("Starting Git Utilities installation...")
    
    bin_dir = Path.home() / ".local" / "bin"
    ssh_dir = Path.home() / ".ssh"
    
    bin_dir.mkdir(parents=True, exist_ok=True)
    ssh_dir.mkdir(parents=True, exist_ok=True)
    
    # Initialize SSH config if needed
    ssh_config = ssh_dir / "config"
    if not ssh_config.exists():
        ssh_config.write_text("# SSH Configuration\n# Auto-generated by git-utils setup\n\n")
        ssh_config.chmod(0o600)
        
    with tempfile.TemporaryDirectory() as temp_dir_str:
        temp_dir = Path(temp_dir_str)
        
        # Copy scripts to temp
        for script in ["git-init", "git-clone", "git-fix"]:
            if (SCRIPT_DIR / script).exists():
                shutil.copy2(SCRIPT_DIR / script, temp_dir / script)
            else:
                print(f"Error: Source script {script} not found in {SCRIPT_DIR}", file=sys.stderr)
                sys.exit(1)

        # Check for interactive mode
        is_ci = os.environ.get("CI")
        is_tty = sys.stdin.isatty()
        
        if is_ci or not is_tty:
            install_unconfigured(temp_dir, bin_dir)
            sys.exit(0)

        # Interactive setup
        (idx, user_choices, user_cases, account_choices, 
         account_cases, host_mappings) = setup_interactive_config()
        
        if idx > 0:
            print(f"Configuring git helper scripts with {idx} identities...")
            
            # Helper to replace in file
            def replace_in_file(filename, replacements):
                fpath = temp_dir / filename
                content = fpath.read_text(encoding='utf-8')
                for k, v in replacements.items():
                    content = content.replace(k, v)
                fpath.write_text(content, encoding='utf-8')

            # Join parts with newlines
            user_choices_str = "\n".join(user_choices)
            user_cases_str = "\n".join(user_cases)
            replace_in_file("git-init", {
                "#PLACEHOLDER_USER_COUNT#": str(idx),
                "# PLACEHOLDER_USER_CHOICES": user_choices_str,
                "# PLACEHOLDER_USER_CASES": user_cases_str
            })

            account_choices_str = "\n".join(account_choices)
            account_cases_str = "\n".join(account_cases)
            replace_in_file("git-fix", {
                "#PLACEHOLDER_ACCOUNT_COUNT#": str(idx),
                "# PLACEHOLDER_ACCOUNT_CHOICES": account_choices_str,
                "# PLACEHOLDER_ACCOUNT_CASES": account_cases_str
            })

            host_mappings_str = "\n".join(host_mappings)
            replace_in_file("git-clone", {
                "# PLACEHOLDER_HOST_MAPPINGS": host_mappings_str
            })
            
            # Install
            for script in ["git-init", "git-clone", "git-fix"]:
                src = temp_dir / script
                dest = bin_dir / script
                shutil.copy2(src, dest)
                dest.chmod(dest.stat().st_mode | 0o111)
            
            print("Git utilities installed successfully!")
            
        else:
            # Fallback to unconfigured
            install_unconfigured(temp_dir, bin_dir)
            print("WARNING: Git utilities installed but not configured")

    print("Git Utilities installation completed successfully!")

if __name__ == "__main__":
    main()
